apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: us-central1-docker.pkg.dev/taskmanager-project-460020/taskmanager-repo/taskmanager-api:3.0
          ports:
            - containerPort: 8080
